# -*- coding: utf-8 -*-
"""GGHackathon2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raa1_1h8mq3cP0TDkX1Q0jV13IDhFhUo

# Introduction to Generating Genius Hackathon 2026

This should guides you through how to use yfinance to get financial data from Yahoo Finance (https://finance.yahoo.com/) and interact with it

## Installing Python Library

`yfinance` is an unofficial open-source python library that provides interface to yahoo finance (more details here: https://pypi.org/project/yfinance/). We will using this library to obtain finance data for this hackation

To install a python library, you can run `pip install <library>` in shell command line. `pip` is a Python package manager, you can read more about it here: https://pip.pypa.io/en/stable/. Installation of a library makes it available to be used by the code we run in this notebook.

To run command line command in Colab, you can use `!<command>` syntax, this tells Colab to run the shell command, so in this case, we will run `!pip install yfinance`
"""

!pip install yfinance

"""# Importing Modules

Let's tell python we are using the following modules:

* `yfinance` to get financial data
* `plotly.graph_objects` to help us plot graphs



"""

import yfinance
import plotly.graph_objects as go
# [TODO] Feel free to add any more modules you want to use for the challenge

"""# Loading Ticker

Let's load up some financial data with the yfinance module, `Ticker` module allows you to access ticker data.

Stocks in yfinance API



"""

# Initialise the Ticker with the stock short code, for instance 'AMZN' for AMZN
amazon = yfinance.Ticker('AMZN')
# Print out the information about the stock, different stock might have different data accessible
print(amazon.info)
# The return value of info method is a dictionary, so we can access each section of the data like so
print("AMAZON Business Summary")
print(amazon.info['longBusinessSummary'])

"""## Loading Historical Market Data

The Ticker object we created also allows us to access historical data

* period:
  * data period to download (Either Use period parameter or use start and end) Valid periods are: 1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, ytd, max
* interval:
  * data interval (intraday data cannot extend last 60 days) Valid intervals are: 1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo
* start:
  * If not using period - Download start date string (YYYY-MM-DD) or datetime.
* end:
  * If not using period - Download end date string (YYYY-MM-DD) or datetime.
* prepost:
  * Include Pre and Post market data in results? (Default is False)
* auto_adjust:
  * Adjust all OHLC automatically? (Default is True)
* actions:
  * Download stock dividends and stock splits events? (Default is True)
(credit: https://aroussi.com/post/python-yahoo-finance)


"""

# Let's say we want to load daily data for the past 6months
price_history = amazon.history(period='6mo', interval='1d')
# [TODO] Play around with this to get different stocks of different interval and time period
# This returns a Pandas Dataframe (read more about it in the next section)
price_history

"""As you can see from the result, the data has 7 columns
  1. Open
    - The price of the stock when the market opens
  1. High
    - The highest price that stock gets to that day
  1. Low
    - The lowest price that stock gets to that day
  1. Close
    - The price of the stock when the market closes
  1. Volume
    - How many stock are traded that day
  1. Dividends
    - How much dividend stock created that day
  1. Stock Splits
    - How much stock are split, read more about stock split here: https://www.investopedia.com/terms/s/stocksplit.asp

This returns a Pandas Dataframe, Pandas is a data science library, feel free to read more about it here: https://pandas.pydata.org/docs/index.html

Pandas is a large library with a lot of functionality, but due to its complexity, we will not discuss it in too much details. But feel free to explore this as part of the challenge if you want to!

Since we don't want to work with the result as Pandas Dataframe, you can use this helper function to convert this to a Dictionary
"""

import pandas as pd
def dataFrameToDict(df):
  data_dict = df.to_dict(orient='index')
  result_dict = {
      str(date.date()): {col: value for col, value in data.items()}
      for date, data in data_dict.items()
  }
  return result_dict
price_history_dict = dataFrameToDict(price_history)

import yfinance as yf
import plotly.graph_objects as go

fig = go.Figure(data=go.Ohlc(x = list(price_history_dict.keys()),
                             open=list([p['Open'] for p in price_history_dict.values()]),
                             high=list([p['High'] for p in price_history_dict.values()]),
                             low=list([p['Low'] for p in price_history_dict.values()]),
                             close=list([p['Close'] for p in price_history_dict.values()])))

fig.show()

"""## Getting other information

## What's the return you'd make holding a shares from X date
"""

import datetime

# Calculate the return of X stock
# E.g. For instance, if you bought X stock at $1 and sold it at $1.20
# The return would be (P_sell - P_buy)/P_buy = (1.20-1)/1 = 0.2 = 20%
def generate_earning_report(start_date, end_date, stock):
  price_history = dataFrameToDict(yfinance.Ticker(stock).history(start=start_date, interval='1d'))
  P_sell = price_history[end_date]['Open']
  P_buy = price_history[start_date]['Open']
  simple_return = (P_sell - P_buy)/P_buy
  print(f"Start Price {P_buy:.2f}")
  print(f"End Price {P_sell:.2f}")
  print(f"Return {simple_return*100:.2f}%")

generate_earning_report(start_date='2023-01-03', end_date='2023-01-30', stock='AAPL')

"""# Exercise: What is the return you'd make if you hold a set of shares from X date

"""

# Write a function that calculates the return of a set of shares
# Input:
# - An dictionary with key being share's name, and value being the weight of the share.
# E.g. [AAPL: 0.5, AMZN: 0.3, GOOG: 0.2]
# - The start date in string with format YYYY-MM-DD
# - -The end date in string with format YYYY-MM-DD
# Output
# - Portfolio Return

"""
# Stock Market Indices

When someone wants a quick way to see how well the biggest companies in the UK are doing — essentially checking the health of the UK’s economy — they can look at a tool called an **index**.

---

## What’s an Index?

A **stock market index** acts like a **scoreboard** for the stock market.  
Instead of reviewing thousands of companies individually, it works by:

1. Selecting a **representative group** of companies.
2. Tracking their stock prices.
3. Combining those prices into **one number** — known as the **index**.

---

## Example: The FTSE 100

A well-known example is the **FTSE 100** (pronounced *footsie*), short for **Financial Times Stock Exchange**.

- It follows the **100 largest companies** listed on the **London Stock Exchange**.
- It provides a snapshot of how the UK’s leading businesses are performing.

"""

# FTSE 100 index ticker on Yahoo Finance
ftse = yfinance.Ticker("^FTSE")

# Get the most recent market data
data = ftse.history(period="1d")

# Print the latest closing price
print("Latest FTSE 100 closing price:")
print(data["Close"].iloc[-1])

import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd

index_tickers = {
    "FTSE 100 (UK)": "^FTSE",
    "S&P 500 (US)": "^GSPC",
    "NASDAQ (US)": "^IXIC",
    "Nikkei 225 (Japan)": "^N225",
    "DAX (Germany)": "^GDAXI"
}

data = yf.download(list(index_tickers.values()), period="6mo")["Close"]
data.columns = list(index_tickers.keys())
data = data.dropna()
normalized_data = data / data.iloc[0] * 100

plt.figure(figsize=(12, 6))
for column in normalized_data.columns:
    plt.plot(normalized_data.index, normalized_data[column], label=column)

plt.title("Performance of Major Stock Market Indexes (Last 6 Months, Normalized)")
plt.xlabel("Date")
plt.ylabel("Index Value (Normalized to 100)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""Indices aren't restricted to the top movers, they can also be specific to a sector such as property."""

import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd

tickers = {
    "iShares UK Property (Sector Proxy)": "IUKP.L"
}

# Download the past 6 months of closing prices
data = yf.download(list(tickers.values()), period="6mo")["Close"]

# Rename columns to human-readable index names
data.columns = list(tickers.keys())

# Drop rows with any missing values
data = data.dropna()

# Normalize to 100
normalized = data / data.iloc[0] * 100

# Plot
plt.figure(figsize=(14, 7))
for col in normalized.columns:
    plt.plot(normalized.index, normalized[col], label=col)

plt.title("Performance of UK and Global Indexes (Last 6 Months, Normalized)")
plt.xlabel("Date")
plt.ylabel("Index Value (Normalized to 100)")
plt.legend(loc="upper left", fontsize="small")
plt.grid(True)
plt.tight_layout()
plt.show()

"""## Challenges Ideas/ Starting point
1. Biggest riser/ faller of stock in the time period
  1. Could you find out the reason for the changes
1. Most popular stock for the month
1. Which business sector does the best in time period
1. Create a website for people to view the returns over time for different stock
1. Create a nice visualisation for the stock price over time
  1. eg. Biggest tech company over time
1. Create a Custom Index
  1. Choose a few companies
  1. Sum up their stock prices
  1. Track how the total changes over time
1. Given X dollars, come up with a strategy to pick a set of stocks that
    1. generates the most profit
    1. has lowest variance in return over time

Google Colab is just for a tutorial, feel free to do the challenges anywhere you like.

"""